Repository johnsson84/HealthCareAB_Frontend, pull requests merged in 2025-01, with the labels that each got.

#18 14 forgot password
  src/App.jsx
  src/components/Login.jsx
  src/components/forgotPassword/ForgotPassword.jsx
  src/components/resetPassword/ResetPassword.jsx
Labels: PRIO 3

#27 added password requirements to reset password
  src/components/forgotPassword/ForgotPassword.jsx
  src/components/resetPassword/ResetPassword.jsx
Labels: PRIO 1

#29 auto redirect reset till login
  src/components/resetPassword/ResetPassword.jsx
Labels: PRIO 2

#38 Appointment History
  src/App.jsx
  src/components/AdminDashboard.jsx
  src/components/UserDashboard.jsx
  src/pages/appointmentHistory/AppointmentHistory.css
  src/pages/appointmentHistory/AppointmentHistory.jsx
Labels: PRIO 1

#65 56 delete edit button in scheduled meeting
  src/components/Appointment-info/A_info.css
  src/components/Appointment-info/A_info.jsx
Labels: PRIO 1

#66 appointment info, admin to doctor role fix
  src/components/Appointment-info/A_info.jsx
Labels: PRIO 1

#68 Book doctor changes
  src/components/Calendar/Calendar.jsx
Labels: PRIO 1

#83 54 facilities
  package-lock.json
  package.json
  src/App.jsx
  src/assets/Hospital-locations.png
  src/components/Header.jsx
  src/components/UserDashboard.jsx
  src/components/facility/Facility.jsx
  src/components/iconLink/IconLink.css
  src/components/iconLink/IconLink.jsx
Labels: PRIO 1

#92 added more enums
  src/components/AddCondition.jsx
Labels: PRIO 1

#94 Feedback fix 2
  src/components/feedback/Feedback.jsx
Labels: PRIO 1

#97 ändrade dom olika knapparna i footer så dom länkar rätt och att alla …
  src/components/AdminDashboard.jsx
  src/components/DoctorDashboard.jsx
  src/components/UserDashboard.jsx
  src/components/footer/Footer.css
  src/components/footer/Footer.jsx
Labels: PRIO 1
